### ISSUE TITLE
Problema ao recuperar a informação da carona solicitada pelo aluno

### ISSUE THREAD

**Issue by gjperes** [tcc-tads-univan/Carpool#2]
Página do frontend que consome: /aluno/carona-solicitada
Serviço consumido: /api/Campi/{campusId}/Student/{studentId}/ride

Erro ao recuperar a carona que foi solicitada com sucesso

![image](https://github.com/tcc-tads-univan/Carpool/assets/61798393/26d41bad-0d9b-4c17-a0ed-3fa7d9691e0f)

**Comment by Mateus-Wosniaki** [comment]
Problema no mock
